name: 'S3 Upload Action'
description: 'This is a GitHub Action that uploads a file to Amazon S3.'
author: 'Hiroyuki Kusu'
branding:
  icon: 'upload-cloud'
  color: 'white'
inputs:
  aws-access-key-id:
    description: ''
    required: true
  aws-secret-access-key:
    description: ''
    required: true
  aws-region:
    description: ''
    required: true
  aws-bucket:
    description: ''
    required: true
  file-path:
    description: ''
    required: true
  destination-dir:
    description: ''
    required: false
  bucket-root:
    description: ''
    default: ''
    required: false
  output-file-url:
    description: ''
    default: 'false'
    required: false
  content-type:
    description: ''
    required: false
  content-disposition:
    description: ''
    required: false
  output-qr-url:
    description: ''
    default: 'false'
    required: false
  qr-width:
    description: ''
    default: '120'
    required: false
  public:
    description: ''
    default: 'false'
    required: false
  expire:
    description: ''
    default: '604800'
    required: false
  alternative-domain-public:
    description: ''
    required: false
  alternative-domain-private:
    description: ''
    required: false
  tags:
    description: 'Optional comma-separated list of S3 object tags (e.g., "Key1=Value1,Key2=Value2").'
    required: false
  checksum-algorithm:
    description: 'Checksum algorithm to use ("CRC32", "CRC32C", "CRC64NVME", "SHA1" or "SHA256").'
    default: "CRC32"
    required: false
  checksum:
    description: 'Expected checksum value of the file to verify integrity before upload.'
    required: false
outputs:
  result:
    description: '`success` or `failure` is set.'
  file-url:
    description: ''
  qr-url:
    description: ''
runs:
  using: 'node24'
  main: 'dist/index.js'